services:
  obsidian:
    image: 'obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    security_opt:
      - seccomp:unconfined #optional
    shm_size: "1gb"
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./vaults:/vaults
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/Chicago
      - FM_HOME=/vaults
      - CUSTOM_PORT=3000
      - CUSTOM_HTTPS_PORT=3001
